export const ICONS = {
  github: "mdi:github",
  linkedin: "mdi:linkedin",
  html: "mdi:language-html5",
  css: "mdi:language-css3",
  javascript: "mdi:language-javascript",
  typescript: "mdi:language-typescript",
  vue: "mdi:vuejs",
  nuxt: "mdi:nuxt",
  scss: "mdi:sass",
  php: "mdi:language-php",
  git: "mdi:git",
  bootstrap: "akar-icons:bootstrap-fill",
  strapi: "simple-icons:strapi",
  java: "whh:java",
  download: "mdi:download",
  gmail: "skill-icons:gmail-light",
  spain: "circle-flags:lang-es",
  england: "circle-flags:en",
  close: "ix:close",
};
